-- =============================================================================
-- DeepTrace — PostgreSQL Extension & Advanced Configuration Migration
-- Run this AFTER `prisma db push` to apply extensions, indexes, RLS, and
-- immutability triggers.
-- Matches exact column casing generated by Prisma.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Required PostgreSQL Extensions
-- -----------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "btree_gin";
CREATE EXTENSION IF NOT EXISTS "unaccent";

-- -----------------------------------------------------------------------------
-- 2. Full-Text Search Index on OCR Content
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_document_pages_ocr_fts
  ON document_pages
  USING GIN (to_tsvector('english', COALESCE("ocrText", '')));

CREATE INDEX IF NOT EXISTS idx_document_pages_ocr_trgm
  ON document_pages
  USING GIN ("ocrText" gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_documents_filename_trgm
  ON documents
  USING GIN ("originalFilename" gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- 3. Partial Indexes for Hot Query Patterns
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_investigations_active
  ON investigations ("organizationId", "createdAt" DESC)
  WHERE "deletedAt" IS NULL
    AND status NOT IN ('ARCHIVED', 'CLOSED');

CREATE INDEX IF NOT EXISTS idx_pipeline_runs_pending
  ON pipeline_runs ("createdAt" ASC)
  WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_pending_retry
  ON webhook_deliveries ("nextRetryAt" ASC)
  WHERE "deliveredAt" IS NULL
    AND "failedAt" IS NULL
    AND attempt < "maxAttempts";

CREATE INDEX IF NOT EXISTS idx_evidence_critical_high
  ON evidence_items ("documentId", "riskPoints" DESC)
  WHERE severity IN ('CRITICAL', 'HIGH');

CREATE INDEX IF NOT EXISTS idx_api_keys_active
  ON api_keys ("keyHash")
  WHERE "isActive" = TRUE;

CREATE INDEX IF NOT EXISTS idx_user_sessions_valid
  ON user_sessions ("tokenHash", "expiresAt")
  WHERE "revokedAt" IS NULL;

-- -----------------------------------------------------------------------------
-- 4. JSONB Indexes for Structured Query Access
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_investigations_metadata
  ON investigations
  USING GIN (metadata jsonb_path_ops);

CREATE INDEX IF NOT EXISTS idx_doc_metadata_fonts
  ON document_metadata
  USING GIN ("fontDictionary" jsonb_path_ops);

CREATE INDEX IF NOT EXISTS idx_pipeline_stages_output
  ON pipeline_stages
  USING GIN ("outputPayload" jsonb_path_ops);

-- -----------------------------------------------------------------------------
-- 5. Row-Level Security (RLS) — Multi-Tenant Isolation
-- -----------------------------------------------------------------------------

ALTER TABLE investigations      ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents           ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_metadata   ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_pages      ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_runs       ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_stages     ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_items      ENABLE ROW LEVEL SECURITY;
ALTER TABLE bounding_boxes      ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_artifacts  ENABLE ROW LEVEL SECURITY;
ALTER TABLE risk_assessments    ENABLE ROW LEVEL SECURITY;
ALTER TABLE risk_signals        ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_sessions      ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_messages      ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs          ENABLE ROW LEVEL SECURITY;
ALTER TABLE custody_events      ENABLE ROW LEVEL SECURITY;
ALTER TABLE users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_keys            ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_endpoints   ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_deliveries  ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any to allow clean re-runs
DROP POLICY IF EXISTS org_isolation_investigations ON investigations;
DROP POLICY IF EXISTS org_isolation_users ON users;
DROP POLICY IF EXISTS org_isolation_api_keys ON api_keys;
DROP POLICY IF EXISTS org_isolation_audit_logs ON audit_logs;
DROP POLICY IF EXISTS org_isolation_webhook_endpoints ON webhook_endpoints;
DROP POLICY IF EXISTS org_isolation_documents ON documents;
DROP POLICY IF EXISTS org_isolation_pipeline_runs ON pipeline_runs;
DROP POLICY IF EXISTS org_isolation_risk_assessments ON risk_assessments;
DROP POLICY IF EXISTS org_isolation_agent_sessions ON agent_sessions;
DROP POLICY IF EXISTS org_isolation_custody_events ON custody_events;
DROP POLICY IF EXISTS org_isolation_evidence_items ON evidence_items;
DROP POLICY IF EXISTS org_isolation_bounding_boxes ON bounding_boxes;
DROP POLICY IF EXISTS org_isolation_evidence_artifacts ON evidence_artifacts;
DROP POLICY IF EXISTS org_isolation_document_metadata ON document_metadata;
DROP POLICY IF EXISTS org_isolation_document_pages ON document_pages;
DROP POLICY IF EXISTS org_isolation_pipeline_stages ON pipeline_stages;
DROP POLICY IF EXISTS org_isolation_risk_signals ON risk_signals;
DROP POLICY IF EXISTS org_isolation_agent_messages ON agent_messages;
DROP POLICY IF EXISTS org_isolation_webhook_deliveries ON webhook_deliveries;

-- RLS Policies for direct organizationId columns
CREATE POLICY org_isolation_investigations ON investigations
  USING ("organizationId" = current_setting('app.current_org_id', TRUE));

CREATE POLICY org_isolation_users ON users
  USING ("organizationId" = current_setting('app.current_org_id', TRUE));

CREATE POLICY org_isolation_api_keys ON api_keys
  USING ("organizationId" = current_setting('app.current_org_id', TRUE));

CREATE POLICY org_isolation_audit_logs ON audit_logs
  USING ("organizationId" = current_setting('app.current_org_id', TRUE));

CREATE POLICY org_isolation_webhook_endpoints ON webhook_endpoints
  USING ("organizationId" = current_setting('app.current_org_id', TRUE));

-- RLS Policies for tables linked via investigations
CREATE POLICY org_isolation_documents ON documents
  USING (
    "investigationId" IN (
      SELECT id FROM investigations
      WHERE "organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_pipeline_runs ON pipeline_runs
  USING (
    "investigationId" IN (
      SELECT id FROM investigations
      WHERE "organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_risk_assessments ON risk_assessments
  USING (
    "investigationId" IN (
      SELECT id FROM investigations
      WHERE "organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_agent_sessions ON agent_sessions
  USING (
    "investigationId" IN (
      SELECT id FROM investigations
      WHERE "organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_custody_events ON custody_events
  USING (
    "investigationId" IN (
      SELECT id FROM investigations
      WHERE "organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

-- Deeper join policies (documents -> evidence -> bounding_boxes)
CREATE POLICY org_isolation_evidence_items ON evidence_items
  USING (
    "documentId" IN (
      SELECT d.id FROM documents d
      JOIN investigations i ON d."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_bounding_boxes ON bounding_boxes
  USING (
    "evidenceItemId" IN (
      SELECT ei.id FROM evidence_items ei
      JOIN documents d ON ei."documentId" = d.id
      JOIN investigations i ON d."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_evidence_artifacts ON evidence_artifacts
  USING (
    "evidenceItemId" IN (
      SELECT ei.id FROM evidence_items ei
      JOIN documents d ON ei."documentId" = d.id
      JOIN investigations i ON d."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_document_metadata ON document_metadata
  USING (
    "documentId" IN (
      SELECT d.id FROM documents d
      JOIN investigations i ON d."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_document_pages ON document_pages
  USING (
    "documentId" IN (
      SELECT d.id FROM documents d
      JOIN investigations i ON d."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_pipeline_stages ON pipeline_stages
  USING (
    "pipelineRunId" IN (
      SELECT pr.id FROM pipeline_runs pr
      JOIN investigations i ON pr."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_risk_signals ON risk_signals
  USING (
    "riskAssessmentId" IN (
      SELECT ra.id FROM risk_assessments ra
      JOIN investigations i ON ra."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_agent_messages ON agent_messages
  USING (
    "agentSessionId" IN (
      SELECT as_.id FROM agent_sessions as_
      JOIN investigations i ON as_."investigationId" = i.id
      WHERE i."organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

CREATE POLICY org_isolation_webhook_deliveries ON webhook_deliveries
  USING (
    "webhookEndpointId" IN (
      SELECT id FROM webhook_endpoints
      WHERE "organizationId" = current_setting('app.current_org_id', TRUE)
    )
  );

-- -----------------------------------------------------------------------------
-- 6. Immutability Triggers — Audit Logs & Custody Events
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION prevent_immutable_table_mutation()
RETURNS TRIGGER AS $$
BEGIN
  IF current_setting('app.allow_test_cleanup', true) = 'true' AND TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION
    'Table "%" is immutable. UPDATE and DELETE operations are forbidden. This record is part of the forensic audit trail.',
    TG_TABLE_NAME
  USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_audit_logs_immutable ON audit_logs;
CREATE TRIGGER trg_audit_logs_immutable
  BEFORE UPDATE OR DELETE ON audit_logs
  FOR EACH ROW
  EXECUTE FUNCTION prevent_immutable_table_mutation();

DROP TRIGGER IF EXISTS trg_custody_events_immutable ON custody_events;
CREATE TRIGGER trg_custody_events_immutable
  BEFORE UPDATE OR DELETE ON custody_events
  FOR EACH ROW
  EXECUTE FUNCTION prevent_immutable_table_mutation();

-- -----------------------------------------------------------------------------
-- 7. Auto-Increment Case Number Function
-- -----------------------------------------------------------------------------

CREATE SEQUENCE IF NOT EXISTS investigation_case_seq
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  CACHE 1;

CREATE OR REPLACE FUNCTION generate_case_number()
RETURNS TEXT AS $$
BEGIN
  RETURN 'DT-PK-' || TO_CHAR(NOW(), 'YYYY') || '-' ||
         LPAD(NEXTVAL('investigation_case_seq')::TEXT, 6, '0');
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 8. Updated-At Auto-Trigger
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'organizations', 'users', 'investigations',
    'documents', 'document_metadata', 'pipeline_runs',
    'risk_assessments', 'investigation_notes',
    'webhook_endpoints'
  ]
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%s_updated_at ON %I', t, t);
    EXECUTE format(
      'CREATE TRIGGER trg_%s_updated_at
       BEFORE UPDATE ON %I
       FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      t, t
    );
  END LOOP;
END;
$$;

-- -----------------------------------------------------------------------------
-- 9. Validation Constraints
-- -----------------------------------------------------------------------------

ALTER TABLE risk_assessments DROP CONSTRAINT IF EXISTS chk_overall_score_range;
ALTER TABLE risk_assessments
  ADD CONSTRAINT chk_overall_score_range
  CHECK ("overallScore" >= 0 AND "overallScore" <= 100);

ALTER TABLE risk_assessments DROP CONSTRAINT IF EXISTS chk_overridden_score_range;
ALTER TABLE risk_assessments
  ADD CONSTRAINT chk_overridden_score_range
  CHECK ("overriddenScore" IS NULL OR ("overriddenScore" >= 0 AND "overriddenScore" <= 100));

ALTER TABLE evidence_items DROP CONSTRAINT IF EXISTS chk_risk_points_non_negative;
ALTER TABLE evidence_items
  ADD CONSTRAINT chk_risk_points_non_negative
  CHECK ("riskPoints" >= 0);

ALTER TABLE evidence_items DROP CONSTRAINT IF EXISTS chk_confidence_range;
ALTER TABLE evidence_items
  ADD CONSTRAINT chk_confidence_range
  CHECK (confidence IS NULL OR (confidence >= 0.0 AND confidence <= 1.0));

ALTER TABLE agent_sessions DROP CONSTRAINT IF EXISTS chk_total_cost_non_negative;
ALTER TABLE agent_sessions
  ADD CONSTRAINT chk_total_cost_non_negative
  CHECK ("totalCostUsd" >= 0.0);

ALTER TABLE document_pages DROP CONSTRAINT IF EXISTS chk_ocr_confidence_range;
ALTER TABLE document_pages
  ADD CONSTRAINT chk_ocr_confidence_range
  CHECK ("ocrConfidence" IS NULL OR ("ocrConfidence" >= 0.0 AND "ocrConfidence" <= 1.0));

ALTER TABLE document_pages DROP CONSTRAINT IF EXISTS chk_page_number_positive;
ALTER TABLE document_pages
  ADD CONSTRAINT chk_page_number_positive
  CHECK ("pageNumber" > 0);

ALTER TABLE investigations DROP CONSTRAINT IF EXISTS chk_priority_range;
ALTER TABLE investigations
  ADD CONSTRAINT chk_priority_range
  CHECK (priority IN (0, 1, 2));

ALTER TABLE bounding_boxes DROP CONSTRAINT IF EXISTS chk_bounding_box_positive;
ALTER TABLE bounding_boxes
  ADD CONSTRAINT chk_bounding_box_positive
  CHECK (width > 0 AND height > 0);

ALTER TABLE webhook_deliveries DROP CONSTRAINT IF EXISTS chk_attempt_valid;
ALTER TABLE webhook_deliveries
  ADD CONSTRAINT chk_attempt_valid
  CHECK (attempt >= 1 AND attempt <= "maxAttempts");
